In [1]:
from forex_python.converter import CurrencyRates
import pandas as pd
import datetime as datetime
import re

In [2]:
df = pd.read_csv("income_by_sex.csv")

df

,Geography,Category,Data Type,Unit,Current Constant,2016,2017,2018,2019,2020,2021
0,World,Disposable Income per Capita by Sex [Male],Socio-economic indicators,USD,Current Prices,"8,613.1","8,980.9","9,407.0","9,518.7","9,231.5","10,295.5"
1,World,Disposable Income per Capita by Sex [Female],Socio-economic indicators,USD,Current Prices,"5,871.6","6,140.4","6,443.3","6,523.2","6,359.3","7,098.1"
2,Asia Pacific,Disposable Income per Capita by Sex [Male],Socio-economic indicators,USD,Current Prices,"4,763.3","5,013.6","5,411.9","5,571.1","5,522.1","6,171.8"
3,Asia Pacific,Disposable Income per Capita by Sex [Female],Socio-economic indicators,USD,Current Prices,"2,787.6","2,913.7","3,150.5","3,251.6","3,256.1","3,613.5"
4,Azerbaijan,Disposable Income per Capita by Sex [Male],Socio-economic indicators,AZN,Current Prices,"4,662.6","5,349.4","5,652.9","6,477.2","6,196.9","6,957.4"
...,...,...,...,...,...,...,...,...,...,...,...
261,NAFTA,Disposable Income per Capita by Sex [Female],Socio-economic indicators,USD,Current Prices,"27,847.4","29,096.3","30,485.6","31,506.4","30,610.7","34,444.1"
262,OECD,Disposable Income per Capita by Sex [Male],Socio-economic indicators,USD,Current Prices,"27,917.2","28,763.2","30,139.5","30,331.8","29,961.1","33,223.0"
263,OECD,Disposable Income per Capita by Sex [Female],Socio-economic indicators,USD,Current Prices,"20,260.2","21,010.2","22,116.2","22,337.8","22,160.7","24,681.9"
264,Sub-Saharan Africa,Disposable Income per Capita by Sex [Male],Socio-economic indicators,USD,Current Prices,"1,740.4","1,773.3","1,818.6","1,857.7","1,597.6","1,700.5"
265,Sub-Saharan Africa,Disposable Income per Capita by Sex [Female],Socio-economic indicators,USD,Current Prices,"1,072.0","1,104.0","1,133.8","1,155.8","1,001.1","1,074.2"

In [3]:
url = "https://www.worldometers.info/geography/alphabetical-list-of-countries/"
tables = pd.read_html(url)
country_list = tables[0]
country_name_list = list(country_list.Country)

country_name_list

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 "CÃ´te d'Ivoire",
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo (Congo-Brazzaville)',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia (Czech Republic)',
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini (fmr. "Swaziland")',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Holy See',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar (formerly Burma)',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine State',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [9]:
row_list = []
for i in range(len(df)):
    if df.Geography[i] not in country_name_list:
        row_list.append(i)

row_list

[0,
 1,
 2,
 3,
 12,
 13,
 26,
 27,
 38,
 39,
 48,
 49,
 54,
 55,
 64,
 65,
 92,
 93,
 128,
 129,
 180,
 181,
 184,
 185,
 186,
 187,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265]

In [12]:
new_data = df.drop(row_list)
new_data = new_data.reset_index(drop = True)

new_data

,Geography,Category,Data Type,Unit,Current Constant,2016,2017,2018,2019,2020,2021
0,Azerbaijan,Disposable Income per Capita by Sex [Male],Socio-economic indicators,AZN,Current Prices,"4,662.6","5,349.4","5,652.9","6,477.2","6,196.9","6,957.4"
1,Azerbaijan,Disposable Income per Capita by Sex [Female],Socio-economic indicators,AZN,Current Prices,"2,346.1","2,707.6","2,876.2","3,312.3","3,184.3","3,591.9"
2,Bangladesh,Disposable Income per Capita by Sex [Male],Socio-economic indicators,BDT,Current Prices,"106,740.4","119,432.6","138,965.7","150,734.7","163,394.1","184,065.3"
3,Bangladesh,Disposable Income per Capita by Sex [Female],Socio-economic indicators,BDT,Current Prices,"54,437.6","60,920.8","70,466.7","76,382.0","82,711.5","93,218.4"
4,Cambodia,Disposable Income per Capita by Sex [Male],Socio-economic indicators,KHR,Current Prices,"4,902,696.4","5,135,554.5","5,415,471.1","5,818,271.9","5,539,109.1","5,704,065.9"
...,...,...,...,...,...,...,...,...,...,...,...
191,Switzerland,Disposable Income per Capita by Sex [Female],Socio-economic indicators,CHF,Current Prices,"44,273.3","43,972.2","44,344.6","44,929.6","46,042.8","48,005.5"
192,Turkey,Disposable Income per Capita by Sex [Male],Socio-economic indicators,TRY,Current Prices,"31,726.2","37,284.5","41,620.9","47,257.7","54,067.0","74,712.0"
193,Turkey,Disposable Income per Capita by Sex [Female],Socio-economic indicators,TRY,Current Prices,"13,959.5","16,368.9","18,649.8","21,559.4","24,838.7","34,572.8"
194,United Kingdom,Disposable Income per Capita by Sex [Male],Socio-economic indicators,GBP,Current Prices,"21,890.5","21,952.5","22,860.8","23,442.0","23,458.0","25,941.1"
195,United Kingdom,Disposable Income per Capita by Sex [Female],Socio-economic indicators,GBP,Current Prices,"17,784.1","18,318.4","19,105.9","19,662.8","19,746.2","21,912.4"